"""empty message

Revision ID: 0977014fc33f
Revises: ddbe359a9ebe
Create Date: 2024-10-15 22:39:01.576875

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0977014fc33f"
down_revision = "ddbe359a9ebe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codename", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "codename", name="_user_codename_uc"),
    )
    op.drop_table("roles")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column("codename", mysql.VARCHAR(length=16), nullable=False),
        sa.Column("user_id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="roles_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="latin1_swedish_ci",
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.drop_table("permissions")
    # ### end Alembic commands ###
