APP_NAME='Flavia'

SECRET_KEY = 'v3rysecret'
JWT_SECRET_KEY = 'v3rysecret'

SQLALCHEMY_DATABASE_URI = "mariadb+pymysql://DB_USER:DB_PASSWORD@localhost/DB_NAME"

MAIL_USERNAME = 'flavia@example.com'
MAIL_SERVER = 'mail.example.com'
MAIL_PORT = 587
MAIL_PASSWORD = 'password'
MAIL_USE_TLS = false

EVERYONE_CAN_REGISTER = true

# Uncomment the following lines in config.test.toml
# TESTING = true
# WTF_CSRF_ENABLED = false